resources:       
  repositories:
  - repository: OwlveyFalcon
    type: github    
    name: owlvey/owlvey_falcon
    endpoint: owlveygithub  
    ref: master
    
variables:
  tag: '$(Build.BuildId)'  

stages:
- stage: ApiBuild
  displayName: Build API project
  jobs:  
  - job: build
    displayName: Build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - checkout: OwlveyFalcon
    - bash: |
        pwd
        ls -a
        echo $(Build.BuildId)
      displayName: list folders    
